on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Golang Email Tests
    steps:
    - name: Build and run go script
      run: go run .
      env:
        MAILSAC_API_KEY:  ${{ secrets.MAILSAC_API_KEY }}
        MAILSAC_USERNAME: ${{ secrets.MAILSAC_PASSWORD }}
        MAILSAC_HOST:     ${{ secrets.MAILSAC_HOST }}
        MAILSAC_PORT:     ${{ secrets.MAILSAC_PORT }}
        EMAIL_FROM:       ${{ secrets.EMAIL_FROM }}
        EMAIL_TO:         ${{ secrets.EMAIL_TO }}