name: Go mail application sample
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Run Golang Email Tests
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build and run go script
      run: go run .
      env:
        MAILSAC_PASSWORD:  ${{ secrets.MAILSAC_PASSWORD }}
        MAILSAC_USERNAME: ${{ secrets.MAILSAC_PASSWORD }}
        MAILSAC_HOST:     ${{ secrets.MAILSAC_HOST }}
        MAILSAC_PORT:     ${{ secrets.MAILSAC_PORT }}
        EMAIL_FROM:       ${{ secrets.EMAIL_FROM }}
        EMAIL_TO:         ${{ secrets.EMAIL_TO }}